// src/components/Main/Header.vue
<template>
    <div class="sticky top-0 left-0 h-12 bg-cyan-950 flex justify-between items-center px-6">
        <div class=""></div>
        <div class="flex items-center">
            <img :src="avt" alt="" class="w-9 h-9 rounded-full mr-2" />
        </div>
    </div>
</template>

<script setup>
import avt from "@/assets/images/ico/avt.webp"
</script>

<style></style>

// src/components/Header.tsx
import React from "react";
import logo from "~/assets/logo.png";

const Header = () => {
    return (
        <div className="h-[60px] px-3 pt-3 w-full flex flex-row justify-between items-center">
            <img
                src={logo}
                alt="onlyone"
                loading="lazy"
                width="160"
                height="280"
                decoding="async"
                style={{ color: "transparent" }}
                className="object-contain"
            />
        </div>
    );
};

export default Header;
